### ISSUE TITLE
Project does not open correctly in Qt Creator

### ISSUE THREAD

**Issue by kubark42** [ArchangelSDY/QtRAR#2]
```
Project ERROR: Could not resolve SDK SDKVersion for 'macosx10.9' using --show-sdk-version
Error while parsing file ~/Documents/QtRAR-master/qtrar.pro. Giving up.
```

This is using macOS 10.15.1 with Qt 5.13.2.

Commenting out the instances of `QMAKE_MAC_SDK = macosx10.9` allow the project to be opened correctly.

There are surprisingly few results when looking for this particular error: https://www.google.com/search?biw=1358&bih=872&ei=j4rNXaG8ErKu5wKfwbCwDQ&q=%22Could+not+resolve+SDK+SDKVersion%22

This is likely a wider problem with the `*.pro` files, as Qt Creator is only running `qmake` in the background and formatting the results, but it's easiest to see when using Qt Creator.

**Comment by ArchangelSDY** [comment]
Looks like my Mac is too old...Removed that line. If you want to specify one you can pass in via qmake command line parameter.
