### ISSUE TITLE
Compile error on Visual Studio

### ISSUE THREAD

**Issue by parisisal** [ArchangelSDY/QtRAR#4]
I have 5 errors :

error LNK2019: unresolved external symbol RARReadHeaderEx "public: bool __cdecl QtRAR::setCurrentFile(class QString const &,enum Qt::CaseSensitivity)" (?setCurrentFile@QtRAR@@QEAA_NAEBVQString@@W4CaseSensitivity@Qt@@@Z)	

similar error also for :
- RAROpenArchiveEx
- RARCloseArchive
- RARProcessFile
- RARSetPasswordW

Can you help me ?

**Comment by ArchangelSDY** [comment]
Please use CMake to generate a Visual Studio solution file and use it for build.
