### ISSUE TITLE
Compiling the library does not generate dll file needed.

### ISSUE THREAD

**Issue by foulinux** [ArchangelSDY/QtRAR#5]
Hello,
I have recently discovered this wrapper and I would like to use it on a project I make.
I downloaded the files, opened qtrar.pro and compiled it on Qt.
In order to use it on my project I import the library and use the headers to write some code.
When I run on debug, QtRAR.dll is needed and it is not generated by compiling the library.
The only files that are generated are obj files, QtRAR.lib and QtRAR.exp.

**Comment by ArchangelSDY** [comment]
Just fixed some link issues. Could you try again?

**Comment by foulinux** [comment]
Hello again,
It worked like a charm.
Thanks a lot kind sir. Really appreciated. :)

**Comment by foulinux** [comment]
Hello again. :/
I stumbled upon an error that cannot be handled.
When I use a correct password to open a rar file with QtRAR::OpenModeList it works fine.
When I use an incorrect password to open a rar file with QtRAR::OpenModeList it works fine.
When I use a correct password to open a QtRARFile it works fine.
But when I use an incorrect password to open a QtRARFile I get an Assert Failure.
Fatal: ASSERT failure in QList<T>::operator[]: "index out of range", file C:\Qt\5.15.2\msvc2019\include\QtCore/qlist.h, line 579 (C:\Qt\5.15.2\msvc2019\include\QtCore/qlist.h)
