### ISSUE TITLE
Fatal: ASSERT failure in QList::operator[]: "index out of range"

### ISSUE THREAD

**Issue by foulinux** [ArchangelSDY/QtRAR#6]
Hello again.
I stumbled upon an error that cannot be handled.
When I use a correct password to open a rar file with QtRAR::OpenModeList it works fine.
When I use an incorrect password to open a rar file with QtRAR::OpenModeList it works fine and doesn't open.
When I use a correct password to open a QtRARFile it works fine.
But when I use an incorrect password to open a QtRARFile I get an Assert Failure.
Fatal: ASSERT failure in QList::operator[]: "index out of range", file C:\Qt\5.15.2\msvc2019\include\QtCore/qlist.h, line 579 (C:\Qt\5.15.2\msvc2019\include\QtCore/qlist.h

**Comment by ArchangelSDY** [comment]
Sounds like a bug. Do you have a full call stack?

**Comment by foulinux** [comment]
Here is a screenshot. Is that enough? If you want more info tell me exactly what you need and I will help.
http://prntscr.com/FVk3sD8t5Pp3
I guess, when you open a .rar file with password correcly, you get the info list but when you try to open a QtRARFile with wrong password it may deny access to the rar itself and blocks the info list? Because I see index out of range. I dunno tbh I am making assumptions. Tbf it is silly to use other password for QtRARFile since a QString variable is to be used for both QtRAR and QtRARFile but I was just testing it.

**Comment by ArchangelSDY** [comment]
I just added some boundary checks to master branch. You can have a try and see if that fixes your issue.

**Comment by foulinux** [comment]
It fixed the issue. Thanks a lot :)
